sp:
  user-service:
    users: "[{\"id\":7, \"username\":\"bbb\",\"password\":\"123\"},{\"id\":8, \"username\":\"def\",\"password\":\"456\"},{\"id\":9, \"username\":\"ghi\",\"password\":\"789\"}]"

spring:
  application:
    name: abc-service
    
server:
  port: 8101

eureka:
  instance:
#    instance-id: 吴限,你好!
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://176.212.33.50:2001/eureka, http://176.212.33.50:2002/eureka

management:
  endpoints:
    web:
      exposure:
        include: refresh
